#!/bin/sh

. /etc/rc.d/init.d/functions

case "$1" in
start)
	echo -n "Remount root to writable ..."
	mount -o remount,rw /
	check_status
	;;
stop)
	echo -n "Remount root to read only ..."
	mount -o remount,ro /
	check_status
	;;
restart)
	;;
*)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
