#!/bin/sh

. /etc/rc.d/init.d/functions

# for i in proc sys dev; do
#   [ ! -d /$i ] && mkdir -p /$i
# done
mount -t proc none /proc
mount -t sysfs none /sys
mount -t tmpfs none /dev

echo -n "Start hotplug ..."
  echo "/sbin/mdev" > /proc/sys/kernel/hotplug
  mdev -s
check_status

[ ! -c /dev/null ] && mknod -m 0666 /dev/null c 1 3
[ ! -c /dev/console ] && mknod /dev/console c 5 1

echo -n "Redirect standard I/O ..."
  IODEV=/dev/ttyAMA0
  [ -c $IODEV ] && exec <$IODEV &>$IODEV
check_status

echo -n "Remount root writable ..."
  mount -o rw,remount / 
check_status

echo -n "Start pseudo terminal ..."
  PTSDEV=/dev/pts
  [ ! -d $PTSDEV ] && mkdir -p $PTSDEV
  mount -t devpts -o mode=0755 devpts $PTSDEV
check_status
