# $Id$
#------------------------------------
PROJDIR?=$(abspath $(dir $(firstword $(wildcard $(addsuffix /proj.mk,. ../..)))))
all-boot: linux;
include $(PROJDIR)/Makefile

#------------------------------------
#------------------------------------
#------------------------------------
#
